import { useEffect, useRef, useState, type Dispatch, type SetStateAction } from "react";
import { api, ApiError } from "../api/client";
import { WebAuth } from "../auth/webAuth";
import { clearDraft, loadDraft, saveDraft } from "../storage/trialDraft";
import { newTrial, remainingRest, trialReducer, type TrialEvent } from "./trialReducer";
import type { Actual, Preview, TrialState } from "./types";

const apk = "https://github.com/Valerochka1337/YarumoGymAndroid/releases/latest";
function tokenFromPath() { const match = location.pathname.match(/^\/r\/([A-Za-z0-9_-]{43})$/); return match?.[1]; }
export function TrialApp() {
  const token = tokenFromPath(); const [state, setState] = useState<TrialState | null>(null); const [loadError, setLoadError] = useState<string>(); const [retry, setRetry] = useState(0); const [storageWarning, setStorageWarning] = useState<string>();
  const dispatch: Dispatch<TrialEvent> = event => setState(previous => previous ? trialReducer(previous, event) : previous);
  const auth = useRef(new WebAuth()); const [now, setNow] = useState(Date.now()); const [timerStatus, setTimerStatus] = useState(""); const [partial, setPartial] = useState(false);
  const [authMode, setAuthMode] = useState<"login" | "register" | "verify">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [code, setCode] = useState("");
  useEffect(() => { if (!token) return; let dead = false; setLoadError(undefined); (async () => { const draft = await loadDraft(token); try { const preview = await api.preview(token); if (!dead) setLoaded(draft, preview, token, setState); } catch (error) { if (dead) return; if (draft) setLoaded(draft, draft.preview, token, setState, error instanceof ApiError && error.status === 404); else setLoadError(error instanceof ApiError && error.status === 404 ? "Ссылка недоступна" : "Не удалось загрузить программу. Проверьте сеть и повторите попытку."); } })(); return () => { dead = true; }; }, [token, retry]);
  useEffect(() => { if (!state || state.phase === "saved") return; saveDraft(state).then(setStorageWarning); }, [state]);
  useEffect(() => { if (state?.phase !== "active") return; const id = window.setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id); }, [state?.phase]);
  useEffect(() => { if (state?.phase === "active" && Math.floor((now - state.startedAt) / 1000) % 15 === 0) setTimerStatus(`Прошло ${Math.max(0,Math.floor((now-state.startedAt)/1000))} секунд`); }, [now, state?.phase, state?.startedAt]);
  useEffect(() => { if (state?.restDeadlineAt && state.restDeadlineAt <= now) dispatch({ type:"expireRest" }); }, [now, state?.restDeadlineAt]);
  useEffect(() => { const onPop=()=>{ if(state?.pendingSaveRequest) return; if(state?.phase === "summary") dispatch({type:"backActive"}); else if(state?.phase === "active") dispatch({type:"backPreview"}); }; addEventListener("popstate",onPop); return()=>removeEventListener("popstate",onPop); }, [state?.phase, state?.pendingSaveRequest]);
  const completed = state?.exercises.flat().filter(set => set.completed).length ?? 0; const total = state?.exercises.flat().length ?? 0;
  if (!token) return <Unavailable title="Некорректная ссылка" />;
  if (!state) return loadError ? <main className="trial-shell"><h1>{loadError}</h1><button onClick={()=>setRetry(value=>value+1)}>Повторить</button></main> : <main className="trial-shell" aria-busy="true"><p>Загружаем программу…</p></main>;
  const save = async () => { if (!state.pendingSaveRequest || !auth.current.token) return; dispatch({ type: "saving" }); try { const receipt = await api.save(state.token, state.pendingSaveRequest, auth.current.token); clearDraft(state.token); dispatch({ type: "saved", ...receipt }); } catch (error) { dispatch({ type: "error", message: error instanceof Error ? error.message : "Не удалось сохранить результаты" }); } };
  const login = async () => { try { await auth.current.csrf(); await auth.current.login({ email, password, deviceName: "Yarumo Browser Trial" }); await save(); } catch (error) { dispatch({ type: "error", message: error instanceof Error ? error.message : "Ошибка входа" }); } };
  const register = async () => { try { await auth.current.csrf(); await auth.current.register({ email, password }); setAuthMode("verify"); } catch (error) { dispatch({ type: "error", message: error instanceof Error ? error.message : "Ошибка регистрации" }); } };
  const verify = async () => { try { await auth.current.verify(email, code); setAuthMode("login"); setPassword(""); } catch (error) { dispatch({ type: "error", message: error instanceof Error ? error.message : "Код не принят" }); } };
  return <main className="trial-shell"><p className="sr-only" aria-live="polite">{timerStatus}</p><header><p className="eyebrow">Yarumo · пробная тренировка</p><h1>{state.preview.title}</h1>{storageWarning && <p role="alert" className="warning">{storageWarning}</p>}{state.error && <p role="alert" className="error">{state.error}</p>}</header>
    {state.phase === "preview" && <PreviewScreen state={state} onStart={() => { dispatch({ type: "start", now:Date.now() }); history.pushState({phase:"active"},""); }} onReset={()=>setPartial(true)} />}
    {state.phase === "active" && <ActiveScreen state={state} now={now} onActual={(e,s,actual) => dispatch({ type: "actual", exerciseIndex:e, setIndex:s, actual })} onComplete={(e,s) => dispatch({ type:"complete", exerciseIndex:e, setIndex:s, now:Date.now() })} onSkip={() => dispatch({ type:"skipRest" })} onFinish={() => completed === 0 ? dispatch({type:"finish",now:Date.now()}) : completed < total ? setPartial(true) : (dispatch({ type:"finish", now:Date.now() }),history.pushState({phase:"summary"},""))} />}
    {state.phase === "summary" && <Summary state={state} completed={completed} onSave={() => dispatch({ type:"auth" })} onBack={() => { dispatch({type:"resume"}); history.back(); }} />}
    {state.phase === "auth" && <section aria-labelledby="auth-title"><h2 id="auth-title" tabIndex={-1}>Сохранить результаты</h2><p>Войдите или зарегистрируйтесь только сейчас. Отмена оставит итоги на устройстве.</p>{authMode === "verify" ? <><label>Код из письма<input value={code} onChange={e=>setCode(e.target.value)} autoComplete="one-time-code" /></label><button onClick={verify}>Подтвердить код</button></> : <><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" /></label><label>Пароль<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={authMode === "login" ? "current-password" : "new-password"} /></label><button onClick={authMode === "login" ? login : register}>{authMode === "login" ? "Войти и сохранить" : "Зарегистрироваться"}</button><button className="text" onClick={() => setAuthMode(authMode === "login" ? "register" : "login")}>{authMode === "login" ? "Создать аккаунт" : "У меня уже есть аккаунт"}</button></>}<button className="text" onClick={() => dispatch({ type:"cancelAuth" })}>Вернуться к итогам</button></section>}
    {state.phase === "saving" && <p aria-live="polite">Сохраняем результаты…</p>}
    {state.phase === "saved" && <section aria-labelledby="saved-title"><h2 id="saved-title" tabIndex={-1}>Результаты сохранены</h2><p>Программа и завершённая тренировка появятся в Yarumo после входа в тот же аккаунт.</p><a className="button" href={apk}>Скачать Yarumo</a></section>}
    {partial && <div className="trial-dialog" role="dialog" aria-modal="true" aria-labelledby="partial-title"><section><h2 id="partial-title" tabIndex={-1}>{state.phase === "preview" ? "Начать заново?" : "Завершить частично?"}</h2><p>{state.phase === "preview" ? "Текущий локальный черновик будет удалён только для этой ссылки." : `В историю попадут только ${completed} выполненных подходов.`}</p><button onClick={() => { setPartial(false); if (state.phase === "preview") { clearDraft(state.token); setState(newTrial(state.token,state.preview)); } else { dispatch({ type:"finish", now:Date.now() }); history.pushState({phase:"summary"},""); } }}>{state.phase === "preview" ? "Удалить черновик и начать" : "Завершить тренировку"}</button><button className="text" onClick={() => setPartial(false)}>Продолжить</button></section></div>}
  </main>;
}
function setLoaded(draft: Awaited<ReturnType<typeof loadDraft>>, preview: Preview, token: string, setState: Dispatch<SetStateAction<TrialState | null>>, revoked = false) { const fresh = newTrial(token, preview); const loaded: TrialState = draft ? { ...fresh, ...draft, preview, phase: draft.saved ? "saved" : draft.finishedAt ? "summary" : draft.phase === "active" ? "active" : "preview", revoked } : { ...fresh, revoked }; if (loaded.phase === "active") { history.replaceState({phase:"preview"},""); history.pushState({phase:"active"},""); } if (loaded.phase === "summary") { history.replaceState({phase:"preview"},""); history.pushState({phase:"active"},""); history.pushState({phase:"summary"},""); } setState(loaded); }
function PreviewScreen({ state, onStart, onReset }: { state: TrialState; onStart: () => void; onReset: () => void }) { return <section><p>≈ {Math.ceil(state.preview.estimatedDurationSeconds / 60)} мин.</p><Program state={state} readOnly /><button disabled={state.revoked} onClick={onStart}>Начать тренировку</button><button className="text" onClick={onReset}>Начать заново</button>{state.revoked && <p role="alert">Ссылка отозвана: локальные итоги можно посмотреть, но начать или сохранить нельзя.</p>}<a className="text-link" href={apk}>Скачать Yarumo</a><p className="hint">Черновик сохраняется на этом устройстве до явного сохранения. Очистка данных сайта удалит его.</p></section>; }
function ActiveScreen({ state, now, onActual, onComplete, onSkip, onFinish }: { state: TrialState; now:number; onActual:(e:number,s:number,a:Actual)=>void; onComplete:(e:number,s:number)=>void; onSkip:()=>void; onFinish:()=>void }) { const rest=remainingRest(state.restDeadlineAt,now); return <section><p>Прошло: {Math.max(0,Math.floor((now-state.startedAt)/1000))} с</p><Program state={state} onActual={onActual} onComplete={onComplete} />{rest > 0 && <aside><strong>Отдых: {rest} с</strong><button className="text" onClick={onSkip}>Пропустить отдых</button></aside>}<button onClick={onFinish}>Завершить тренировку</button></section>; }
function Program({ state, readOnly=false, onActual, onComplete }: { state:TrialState; readOnly?:boolean; onActual?:(e:number,s:number,a:Actual)=>void; onComplete?:(e:number,s:number)=>void }) { return <div className="program">{state.preview.exercises.map((exercise,e)=><fieldset key={e}><legend>{e+1}. {exercise.name} <span>{exercise.type} · отдых {exercise.restSeconds} с</span></legend>{exercise.sets.map((plan,s)=> <SetRow key={s} plan={plan} type={exercise.type} state={state.exercises[e][s]} index={s+1} readOnly={readOnly} onChange={actual=>onActual?.(e,s,actual)} onComplete={()=>onComplete?.(e,s)} />)}</fieldset>)}</div>; }
function SetRow({ plan,type,state,index,readOnly,onChange,onComplete }: { plan:Preview["exercises"][number]["sets"][number]; type: string; state:TrialState["exercises"][number][number]; index:number; readOnly:boolean; onChange:(a:Actual)=>void; onComplete:()=>void }) { const change=(key:keyof Actual,value:string)=>onChange({ ...state.actual, [key]: value === "" ? null : Number(value) }); const input=(key:keyof Actual,value:number|null,step="1",min="0")=><input type="number" min={min} step={step} disabled={readOnly} value={value ?? ""} onChange={e=>change(key,e.target.value)} />; return <div className="set"><strong>Подход {index}</strong>{type === "STRENGTH" && <><label>Вес, кг{input("weightKg",state.actual.weightKg ?? plan.weightKg,"0.1")}</label><label>Повторы{input("reps",state.actual.reps ?? plan.reps)}</label></>}{type !== "STRENGTH" && <label>Длительность, с{input("durationSec",state.actual.durationSec ?? plan.durationSec)}</label>}{type === "CARDIO" && <><label>Скорость, км/ч{input("speedKmh",state.actual.speedKmh ?? plan.speedKmh,"0.1")}</label><label>Наклон, %{input("inclinePct",state.actual.inclinePct ?? plan.inclinePct,"0.1","-100")}</label></>}{!readOnly && <button aria-pressed={state.completed} onClick={onComplete}>{state.completed ? "Выполнено" : "Отметить выполненным"}</button>}</div>; }
function Summary({ state, completed, onSave, onBack }: { state:TrialState; completed:number; onSave:()=>void; onBack:()=>void }) { const mins=Math.max(0,Math.round(((state.finishedAt ?? state.startedAt)-state.startedAt)/60000)); const facts=state.exercises.flatMap((sets,e)=>sets.flatMap((set,s)=>set.completed?[{e,s,set}]:[])); const description=(e:number,a:Actual)=>{ const type=state.preview.exercises[e].type; return type==="STRENGTH"?`${a.weightKg} кг × ${a.reps}`:type==="TIMED"?`${a.durationSec} с`:`${a.durationSec} с${a.speedKmh===null?"":`, ${a.speedKmh} км/ч`}${a.inclinePct===null?"":`, наклон ${a.inclinePct}%`}`; }; return <section aria-labelledby="summary-title"><h2 id="summary-title" tabIndex={-1}>Итоги тренировки</h2><p>Длительность: {mins} мин. Выполнено подходов: {completed}.</p><ul>{facts.map(({e,s,set})=><li key={`${e}-${s}`}>{state.preview.exercises[e].name}, подход {s+1}: {description(e,set.actual)}</li>)}</ul><button disabled={state.revoked || completed===0} onClick={onSave}>{state.pendingSaveRequest ? "Повторить сохранение" : "Сохранить результаты"}</button>{state.pendingSaveRequest ? <p role="status">Сохранение подготовлено. Повтор будет отправлен с теми же данными; результаты больше не редактируются.</p> : <button className="text" onClick={onBack}>Вернуться к редактированию</button>}{state.revoked && <p role="alert">Сохранение заблокировано: ссылка отозвана.</p>}</section>; }
function Unavailable({ title }: { title:string }) { return <main className="trial-shell"><h1>{title}</h1><p>Проверьте ссылку или попросите автора отправить новую.</p></main>; }
